api_version = "2026-01"
uid = "8ddfe14a-36a8-cce7-3014-367d5c52e4785a42444a"

[[extensions]]
name = "VAT Relief (exact)"
handle = "vat-relief-discount"
type = "function"
description = "Removes the exact VAT portion from cart lines with a HMRC VAT relief declaration."

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.capabilities]
  discount_classes = ["ORDER"]
