# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d0589c6e7756aea84becc989391f687d"
name = "XSTO VAT Relief"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
